### ISSUE TITLE
Poročilo in zemljevid

### ISSUE THREAD

**Issue by jaanos** [MarvinHerzog/APPR-2015-16#1]
V poročilu kličeš program `obdelava.r`, a imata ustrezna datoteka končnico `.R` (velika črka!). Tako napiši tudi pri klicanju, saj so nekateri sistemi občutljivi na velikost črk.

Zemljevid uvažaš neposredno s funkcijo `readShapeSpatial`, a zemljevida nimaš (in tudi nočeš imeti) v repozitoriju, saj ti `.gitignore` to preprečuje. Namesto tega raje uporabi funkcijo `uvozi.zemljevid`.

Da ti v poročilo ne bo izpisovalo obvestil ob uvozu knjižnic, vse klice ukazov `library` in `require` premakni iz `obdelava.R` v `lib/libraries.r`. Druga možnost bi bila, da pri bloku, kjer kličeš `uvoz.r`, nastaviš `results='hide'` in `message=FALSE`, da se ta obvestila ne izpisujejo. Seveda v poročilu opiši svojo tematiko in uvožene podatke ter nariši še kak graf.

Vidim, da imaš narejen tudi vmesnik v Shinyju. Tega lahko seveda uporabiš za predstavitev, a vseeno poskrbi tudi za poročilo.

**Comment by MarvinHerzog** [comment]
opravljeno.
